# Global 
test: true
verbose: true
validate_xml_tags: false

Dataset:
  name: "CheeSpeech"
  uses_region: true

ASR:
  type: "Nvidia-Parakeet"    # Options: Whisper, ElevenLabs, Nvidia-Parakeet
  model_name: "Nvidia-Parakeet" 
  Whisper:
    model_size: "turbo"    # Options: tiny, base, small, medium, large, turbo
  ElevenLabs:
    api_key: "insert key"
Normalization:
  remove_all_punctuation: true    # if true, removes all punctuation. If false, keeps grammatically relevant punctuation (.,;?!).
  normalize_uppercase: true
  filler_symbol: ''    # Symbol to replace the content of <filler> tags. If empty, removes the tag and its content.
  special_attribute_config:   # Tags that when replaced, keeps the value of the attribute instead of the internal text.  
    # tag_name: attribute_name
    alargamiento: "palabra"